#!/usr/bin/env python3
import colors as c
import time
print(c.clear)
snake = '''
SNAAAAAAAAAAAAAAAAAAAAAAAKE!!!!!
SNAAAAAAAAAAAAAAAAAAAAAAAKE!!!!!
SNAAAAAAAAAAAAAAAAAAAAAAAKE!!!!!
'''
while True:
    for verse in range(4):
        for count in range(12):
            print(c.red + 'Badgers! ')
            time.sleep(0.3)
        print(c.reset)
        if verse > 3:
            for count1 in range(2):
                print(c.orange + 'SNAAAAAAAAAAAAAAAAAAAAKE')
                time.sleep(0.75)
                print(c.reset)
        if verse < 3:
            for count in range(2):
                print(c.orange + 'Mushroom')
                time.sleep(0.75)
                print(c.reset)

        print(c.reset)
    print(snake)
    
      
