#!/usr/bin/env python3

import colors as c 
from util import ask
import string

print(c.clear + c.red + '''
Welcome to Bonus Words!!
''' + c.reset)

with open('word_libs.d/personal_ad','r') as f:
    text = f.read()

words = {i[1]: None for i in string.Formatter().parse(text) if i[1]}

for keyword in words:
    words[keyword] = c.base3 + ask(keyword.rstrip('0123456789') + ': ',
                        lower=False) +  c.reset

print(c.clear + text.format(**words))
