#!/usr/bin/env python3

import colors as c 
from util import ask

text = '''
Once upon a time, there was a {noun1} named {name}, now {gender} wasn't just any type 
of {noun1}, {gender} was a special breed of them called the {plural1}. Now this breed
went on many adventures with {famous_person}, and also they would explore the deep 
parts of the {specific_place}, which was very dangerous since there are {robotic_machine}'s
inside, and there was the leader named {name2}. So after a while in the year {year},
the hero named {name} was born! And changed the whole tribe of the {plural1}! But one
day, something happened, a {natural_disaster} have come! And {name} died. So in the end,
the hero {name} saved the day from the evil {name2},.The tribe was very {emotion}, since he died.
But the tribe shall always remember {name} from the {noun2} they had from him... 
'''


words = {
    "gender" : {"desc": "gender (he, or she)"},
    "noun1" : {},
    "name" : {},
    "plural1" : {},
    "famous_person" : {},
    "specific_place" : {},
    "robot" : {"desc": "robot (like turret)"},
    "name2" : {},
    "year" : {},
    "natural_disaster" : {},
    "noun2" : {},
    "emotion" : {},
}

print(c.clear + c.yellow + '''
Hello, Welcome to MadLibs. Just Enter Your Answers Below...
''' + c.reset)


answers = {}
for key in words:
    desc = words[key].get('desc')
    if desc:
        prompt = desc.title()
    elif key.startswith('noun'):
        prompt = 'Noun'
    elif key.startswith('name'):
        prompt = 'Name'
    elif key.startswith('plural'):
        prompt = 'Plural Noun'
    else:
        prompt = key.replace('_',' ').title().rstrip('0123456789')
    answers[key] = ask(prompt,lower=False,end=": ")

print(c.clear + "Personal Ad:\n" + text.format(**answers))
