#!/usr/bin/env python3


import colors as c
import time
print(c.reset)
b = c.base3
r = c.reset
print(c.yellow + 'Mmmmmm, multiplication tables. ')
time.sleep(1)
print(c.reset)
number = input(c.yellow + 'What number do you want to learn about?? ')
time.sleep(1)
print('Table for {}:'.format(number))

for times in range(1, 100000000000000001 ):
    answer = times * int(number)
    form = b + '{}' + r + ' x ' + b + '{}' + r + ' = ' + b + '{}'
    print(form.format(number,times,answer))
    time.sleep(1)

