#!/usr/bin/env python3

import random
import time
import colors as c
from utils import ask

print(c.clear + c.magenta + 'Welcome to the Pink Fluffy Unicorns Quiz!')
time.sleep(0.5)
print(c.magenta + 'Lets see what you know about this...')

def q1():
    answer = ask("What color are the unicorns?")
    if answer == 'pink':
        return True
    return False
    
def q2():
    answer = ask("Where are they dancing?")
    if answer.start("rainbow"):
        return True
    return False

def q3():
    answer = ask("Please use one word to describethe texture of their magical fur:")
    if answer.startswith("smile"):
        return True
    return False
    
        

