#!/usr/bin/env python3

###Pick one to be the quiz
#import pfudor as quiz
import my_quiz as quiz

import colors as c
import random

print(c.clear)
print(quiz.intro)
while quiz.questions:
    question_function = random.choice(quiz.questions)
    is_correct = question_function()
    if is_correct:
        quiz.questions.remove(question_function)


