#!/usr/bin/env python3
#import pfudor as quiz
import colors as c
import my_quiz as quiz
print(c.clear)
print(quiz.intro)
while quiz.questions:
    question_function = random.choice(quiz.questions)
    is_correct = question_function()
    if is_correct:
        quiz.questions.remove(question_function)


