#!/usr/bin/env python3


import random
import colors as c
import time

dice = []

dice.append(''' 
 -------
|       |
|   o   |
|       |
 -------  
''')

dice.append('''
 -------
| o     |
|       |
|     o |
 -------
''')

dice.append('''
 -------
| o     |
|   o   |
|     o |
 -------
''')

dice.append('''
 -------
| o   o |
|       |
| o   o |
 -------
''')

dice.append('''
 -------
| o   o |
|   o   |
| o   o |
 -------
''')

dice.append('''
 -------
| o   o |
| o   o |
| o   o |
 -------
''')
num = 1
while True:
    print(c.clear, end="")
    for count in range(num):
        die = random.choice(dice)
        print(c.random_color() + die + c.reset, end="")
    while True:
        try:
            new_num = input() 
        except KeyboardInterrupt:
            exit(0)
        if new_num:
            try:
                num = int(new_num)
                break
            except ValueError:
                print(c.magenta + 'needs a number')
