#!/usr/bin/env python3  
import colors as c
import time
import random
seconds = 1
which = input('Tenths or Seconds? ').strip().lower()

if 't' in which:
    while True:
        time.sleep(.1)
        print(c.random_color() + str(seconds) + ' seconds')
        seconds += 1

elif 's' in which:
    while True:
        time.sleep(1)
        print(c.random_color() + str(seconds)  + ' seconds' )
        seconds += 1
else:
    print('Say one for goodness sake!! ')
