#!/usr/bin/env python3
from utils import ask
import colors as c

while True:
    print(c.clear) 
    print(c.yellow + 'Do you like waffles?' + c.reset)
    waffles = input(c.base3 + '> ').strip().lower()
    if 'y' in waffles:
        print(c.blue + 'Do you like pancakes?' + c.reset)
        pancakes = input(c.base3 + '> ').strip().lower()
        if 'y' in pancakes:
            print(c.red + 'Do you like French Toast?' + c.reset)
            toast = input(c.base3 + '> ').strip().lower()
            if 'y' in toast:
                print(c.green + "Do do da do, can't wait to get a mouthful!" + c.reset)
                break
    if waffles == 'no':
        print(c.pink + 'Well, I do like waffles...' + c.reset)
        break
        if pancakes == 'no':
            print(c.base3 + 'Well, I do like pancakes...' + c.reset)
            break
            if toast == 'no':
                print(c.green + 'Well, I do like french toast...' + c.reset)
                break

