#!/usr/bin/env python3

import colors as c
import time 


while True:
    for verse in range(4):
        for count in range(12):
            print('Badger')
            time.sleep(0.3)
        if verse < 3:
            print(c.clear)
            for count in range(2):
                print(c.clear)
                print('Mushroom')
                time.sleep(0.50)
                print('Mushroom')
        if verse > 3:
            for count in range(2):
                print(c.clear)
                print('SNAKE!!!!!!!!')
    
    
    
    print(c.clear)           
    print('SNAKE')
