#!/usr/bin/env python3

import colors as c
import time

sleep = 1
m = 0

while True:
  for m in range(10000):
    binform = c.clear + c.yellow + '{}: {:04b}' + c.reset
    print(binform.format(m,m))
    time.sleep(sleep)
