#!/usr/bin/env python3 

import colors as c

try:
    while True:
        print(c.red + 'm' + c.orange + 'e' + c.yellow + 'o' + c.green + 'w' + c.blue + '!', end = '')
except KeyboardInterrupt:
    exit()
